### ISSUE TITLE
添加汉化Mystical-Block-2.7.1

### ISSUE THREAD

**Issue by SyCrr** [Pasuu/Modpack-pro#2]
[[Mystical Block.zip](https://github.com/Pasuu/Modpack-pro/files/12385184/Mystical.Block.zip)
](https://www.bilibili.com/read/cv25832790?spm_id_from=333.999.list.card_opus.click)

**Comment by SyCrr** [comment]
链接：https://pan.baidu.com/s/1I15orHJijtgVUy3J78VEHA 

提取码：SyCr 作者：神域传人 https://www.bilibili.com/read/cv25832790?spm_id_from=333.999.list.card_opus.click 出处：bilibili

**Comment by Pasuu** [comment]
收到，已添加进网站，谢谢~
